# docker-compose up --build
# docker logs nome_container

version: '3.8'

services:
  transiti:
    container_name: transiti
    build:
      context: ./backend-transiti
      dockerfile: Dockerfile
    volumes:
      - ./backend-transiti:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - pagamenti

  pagamenti:
    container_name: pagamenti
    build:
      context: ./backend-pagamenti
      dockerfile: Dockerfile
    volumes:
      - ./backend-pagamenti:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge
