version: '3.8'

services:
  transiti:
    container_name: transiti
    build:
      context: ./backend-transiti
      dockerfile: Dockerfile
    volumes:
      - ./backend-transiti:/usr/src/app # Monta directory nel container
      - /usr/src/app/node_modules
    ports:
      - "3000:3000" # Porta 3000 container su porta 3000 host
    env_file:
      - .env
    depends_on:
      - db
      - pagamenti
    networks: # Rete in cui il servizio sarà collegato
      - backend

  pagamenti:
     container_name: pagamenti
     build:
       context: ./backend-pagamenti
       dockerfile: Dockerfile
     volumes:
       - ./backend-pagamenti:/usr/src/app # Monta directory nel container
       - /usr/src/app/node_modules
     ports:
       - "3001:3001"
     env_file:
       - .env
     depends_on:
       - db
     networks: # Rete in cui il servizio sarà collegato
       - backend

  db:
    container_name: postgres
    image: postgres:13
    environment: # Variabili d'ambiente per configurare Postgres
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks: # Rete in cui il servizio sarà collegato
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge # Driver bridge permette ai container di comunicare tra loro